nop %sh{
	mkdir -p "$kak_config/autoload"
	[ ! -e "$kak_config/autoload/standard-library" ] && \
		ln -s "$kak_runtime/rc" "$kak_config/autoload/standard-library"
}

evaluate-commands %sh{
	mkdir -p $HOME/.config/kak/autoload/bundle/
	[ ! -e "$kak_config/autoload/bundle" ] && \
            git clone https://codeberg.org/jdugan6240/kak-bundle $HOME/.config/kak/autoload/bundle/kak-bundle
}

bundle kak-lsp https://github.com/kak-lsp/kak-lsp %{
	map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"
}

bundle kakboard https://github.com/lePerdu/kakboard %{
	hook global WinCreate .* %{ kakboard-enable }
}

bundle smarttab https://github.com/andreyorst/smarttab.kak %{} %{
	hook global WinSetOption .* %{
        	noexpandtab
        	set-option global softtabstop 8
	}
}

bundle luar https://github.com/gustavo-hms/luar %{
	set-option global luar_interpreter luajit
}

bundle peneira https://github.com/gustavo-hms/peneira %{
	require-module peneira
	hook global WinCreate .* %{ add-highlighter window/number-lines number-lines -relative -hlcursor }
}

bundle-noload base16-gruvbox https://github.com/andreyorst/base16-gruvbox.kak

bundle-install-hook base16-gruvbox %{
	# Post-install code here...
	mkdir -p ${kak_config}/colors
	ln -sf "${kak_opt_bundle_path}/base16-gruvbox" "${kak_config}/colors/"
}

colorscheme base16-gruvbox-dark-hard # or any other variant

bundle kakoune-ghwiki https://gitlab.com/Screwtapello/kakoune-ghwiki %{} %{
	ghwiki-enable
}

# Set basic options

# Set relative line numbers
add-highlighter global/ number-lines -relative -hlcursor

# Keymaps
map global normal <a-j> 'xdp'
map global normal <a-k> 'x"aZy<a-;>kPZ"azdz'

map global user f %{:peneira-files<ret>} -docstring "Find files"

hook global InsertCompletionShow .* %{
	map window insert <tab> <c-n>
	map window insert <s-tab> <c-p>
}

hook global InsertCompletionHide .* %{
	unmap window insert <tab> <c-n>
	unmap window insert <s-tab> <c-p>
}

# Tab stuff
set-option global tabstop 8
set-option global indentwidth 0

add-highlighter global/ wrap -word -indent

# Start the lsp
lsp-enable
