version = 3
final_space = true

[palette]
  aqua = '#698d6a'
  bg = '#282828'
  blue = '#458588'
  gray = '#a89984'
  green = '#98971a'
  purple = '#b16286'
  red = '#cc241d'
  yellow = '#d79921'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:purple'

    [blocks.segments.properties]
      style = 'full'
  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    template = '<p:green,>git:(</><p:red>{{.HEAD }}</><p:green>)</> '
    [blocks.segments.properties]
      branch_icon = ''
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:blue{{end}}"
    ]
    background = 'transparent'
    template = '$>'
