version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
        type = 'path'
        style = 'plain'
        background = 'transparent'
        foreground = 'p:mauve'

        [blocks.segments.properties]
            style = 'full'

    [[blocks.segments]]
        type = 'git'
        style = 'plain'
        foreground = 'p:green'
        background = 'transparent'
        template = '{{ .HEAD }} {{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}<cyan>{{ if gt .Behind 0 }} ↓{{ end }}{{ if gt .Ahead 0 }} ↑{{ end }}</>'

        [blocks.segments.properties]
            branch_icon = ''
            commit_icon = '@'
            fetch_status = true

    [[blocks.segments]]
        type = 'text'
        style = 'plain'
        foreground_templates = [
            "{{ if gt .Code 0 }}p:red{{end}}",
            "{{ if eq .Code 0 }}p:sky{{end}}",
        ]
        background = 'transparent'
        template = "〉"

[transient_prompt]
    foreground_templates = [
        "{{ if gt .Code 0 }}p:red{{end}}",
        "{{ if eq .Code 0 }}p:sky{{end}}",
    ]
    background = 'transparent'
    template = '〉 '

[palette]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
