import = [
    "~/.config/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"
]

shell = "zsh"

[window]
blur = true
startup_mode = "Maximized"
#dynamic_title = false

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
size = 12.0
